name: Android

on:
  push:

jobs:

  build:
    name: Build and create APK

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-24.04

    env:
      App_Project_File: src/Vocup.Android/Vocup.Android.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install .NET SDK
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore .NET Workloads
      run: dotnet workload restore $App_Project_File

    - name: Restore NuGet packages
      run: dotnet restore $App_Project_File

    - name: Decode Keystore
      run: |
        echo "${{ secrets.BASE64_ENCODED_JKS }}" | base64 --decode > src/Vocup.Android/vocup-android.jks

    - name: Build and create AAB
      if: matrix.configuration == 'Debug'
      run: |
        dotnet build \
          --no-restore \
          --configuration ${{ matrix.configuration }} \
          $App_Project_File
    
    - name: Build and create signed AAB
      if: matrix.configuration == 'Release'
      run: |
        dotnet build \
          --no-restore \
          --configuration ${{ matrix.configuration }} \
          -p:AndroidKeyStore=True \
          -p:AndroidSigningStorePass=${{ secrets.JKS_PASSWORD }} \
          -p:AndroidSigningKeyPass=${{ secrets.JKS_PASSWORD }} \
          $App_Project_File

    - name: Upload build artifacts
      if: matrix.configuration == 'Release' && startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: AAB
        path: src/Vocup.Android/bin/Release/net10.0-android/org.vocup-Signed.aab
